### ISSUE TITLE
Write a 155 character description about DaBible Foundation

### ISSUE THREAD

**Issue by sanmiayotunde** [sanmiayotunde/DaBible-Foundation#1]
We need 75 words that describe what we do at DaBible Foundation. This "meta-description" will be used on every web application such as our website.

![image](https://user-images.githubusercontent.com/23180033/106560565-d72c5b80-64ec-11eb-9f8f-6dcd2994af4d.png)

**Comment by emmanlex** [comment]
- [ ] I will invest time in dissecting popular meta descriptions that provide similar services to DaBible Foundation. 

![Meta1](https://user-images.githubusercontent.com/50557337/106566235-a997e000-64f5-11eb-9505-03c1f7ecd384.png)
![Meta2](https://user-images.githubusercontent.com/50557337/106566237-aa307680-64f5-11eb-82a6-11a38c57b9ea.png)

Take note that a defined limit for a meta description is a recommended 155 characters not the 75 words requested. @sanmiayotunde 

- [ ] I will provide a meta description that is captivating and gives a good description of the site's services for your review.

**Comment by sanmiayotunde** [comment]
Awesome!!!!!! @emmanlex this is super good! Let's shoot for 155 characters.

**Comment by emmanlex** [comment]
First Attempt (META DESCRIPTION)
Yes! FREE Audio Bible in African languages. Only on DaBible.com, you can find Yoruba and Pidgin audio bibles apps. Download. Listen! There’s more to come. 
Please review and provide feedback @sanmiayotunde 

- [ ] Did I satisfy my task requirement. if box not checked make subsequent attempts.

**Comment by sanmiayotunde** [comment]
We just created a survey to know what people prefer from the choices above

https://forms.gle/3k6gR5QmqwnbKSYC7

Thanks

**Comment by sanmiayotunde** [comment]
The results of the survey

![image](https://user-images.githubusercontent.com/23180033/106708745-014b4f80-65b9-11eb-90fc-a43c41bf4bce.png)


![image](https://user-images.githubusercontent.com/23180033/106708720-f7c1e780-65b8-11eb-9974-02b4b509e438.png)

**Comment by emmanlex** [comment]
The results of the survey were mildly expected but with actual survey report we have unequivocally come to a decision on using the First Meta description. 
@sanmiayotunde please update the DaBible Foundation description with this meta description.
