### ISSUE TITLE
Updates On Title tags for Homepage

### ISSUE THREAD

**Issue by emmanlex** [sanmiayotunde/DaBible-Foundation#16]
The title tag we agreed upon is not appearing on the search result of the dabible.com home page. 
@sanmiayotunde 

- [x] Please change the homepage title tag as stated. 

**Title tag**
Free Audio Bible in Yoruba & Pidgin | DaBible Foundation

![Screen Shot 2021-02-09 at 11 52 25 AM](https://user-images.githubusercontent.com/50557337/107406218-cf148300-6acd-11eb-9be2-422b6ae8383e.png)

Thanks

**Comment by sanmiayotunde** [comment]
This issue is not resolved, lets check on the end of this milestone for changes reflection on google.
