### ISSUE TITLE
Welcome to DaBible Foundation Blog post MVC 1

### ISSUE THREAD

**Issue by sanmiayotunde** [sanmiayotunde/DaBible-Foundation#2]
Hello,

We currently have a HIGH ranking page on our previous www.yorubabible.net website. Huge tons of traffic is going to the old website which is not beneficial to us. 

Write well-detailed content that welcomes users to DaBible Foundation. 

**GOAL:** The welcome blog post must rank on Google Search Engine's page 1.

The content should cover the following

- [ ] Welcome to DaBible Foundation
- [ ] Who are we
- [ ] What do we do
- [ ] Who do we cater for
- [ ] Where are we
- [ ] What products do we have, app, solar, website.
- [ ] What can the products do for our users.
- [ ] What will people benefit from our website or mobile app.
- [ ] What are the features of our app.
- [ ] Other vital parts

 Our stakeholders should be educated about what they will get from DaBible and what we stand for.

**Old URL:** http://yorubabible.net/welcome-to-yoruba-audio-bible/
**New URL:** https://dabible.com/blog/welcome-to-yoruba-audio-bible/

Thanks.

**Comment by emmanlex** [comment]
**First MVP for this task**  

Many thanks to our listeners and app users for your support. Be kindly informed that this site, Yorubaaudiobible.net is now down and would no longer be in use. Instead, please visit DaBible.com for full audio recordings and readings of the Yoruba bible. DaBible.com is owned and managed by DaBible Foundation. Our goal in DaBible Foundation is to provide clear and audible bible translation in various native languages. We are devoted to bringing you the word of God in the comfort of your homes, on your computers and your mobile devices. Our Mobile App has been built to be simple and easy to navigate. DaBible Foundation from its very conception has been led by God's divine direction and we put him foremost in all we do. All team members are volunteers, who work to provide the best experience we can offer on all our platforms. You can see find out how it all started on OUR STORY page. 

Presently, we have two apps available for downloads, the Yoruba audio bible app you know and love is still available on apple store and google play store. Our newly released Pidgin audio bible app is also available on the apple and google play stores, Just click this link for more info (https://dabible.com/pidgin/). Released in 2020 our pidgin audio bible is our second production of the like. With both old and new testament translated to pidgin, the Pidgin bible is the very first of its kind. You can find both our apps on the apple store and google pay store available for both IOS and android downloads for FREE. We have gone on one step further in our mission of providing text and audio transcribed and recorded in familiar African languages. So go on to your apple stores and google stores and get a copy of your very own Pidgin audio bible app. Our apps are developed by Dabible.com to be easy to navigate and we have features for offline downloads. So wherever you are, as along as you have an internet access you can download the files to your phone and can then listen to them whenever you want. Easy and convenient.

Similarly, the Yoruba audio bible app, created by DaBible foundation remains available for downloads on apple and android devices. We have been constantly making updates and we have our apps ready for offline mode. Just like with the Pidgin audio bible app, you can download the audio files onto your phone and can listen at your own convenience. 

In other news, we are pleased to inform you that we are soon to release a Hausa audio bible too. Visit https://dabible.com/hausa/ for updates on our release dates to know the when and how you can access this amazing content. 

As you may already know, our contents are all FREE. We are dedicated to our mission of getting the word of God across to people in their own tongue. Lastly, we are expressly grateful to our donors for their support, the almighty God will continue to bless the works of your hand. 

On this note, let me be the first to welcome you to our new and ever improving DaBible.com.

**Comment by emmanlex** [comment]
please insert links appropriately and in context. Ask for more info if needed @sanmiayotunde

**Comment by sanmiayotunde** [comment]
@emmanlex Thanks for this content, it's now published on https://dabible.com/blog/welcome-to-yoruba-audio-bible/
