### ISSUE TITLE
Create missionary content for Leviticus Makpa - MVC 2

### ISSUE THREAD

**Issue by sanmiayotunde** [sanmiayotunde/DaBible-Foundation#24]
Re-write this blog post on Leviticus Makpa, one of our missionaries in Niger State.

Link: https://dabible.com/blog/missions/introducing-our-leviticus-gamaliel-missionary-field-in-niger-state/

Related: #23

**Comment by emmanlex** [comment]
MVC 2
Missionary Quest Blog [H1]
As part of our community outreach program, DaBible has begun to reach out to missionaries in obscure places in the continent of Africa.  On this edition of our missionary quest blog we will be introducing Leviticus Makpa from Nigeria. 

Leviticus is a missionary based in Niger State, to a few rural communities.  I was opportune to get acquainted with this remarkable gentleman. We chatted a bit and I requested that he share a bit about himself. This is what he had to say about himself and his mission. 

Introducing Leviticus Makpa's Missionary Field in Niger State [H2]
[Place image of Leviticus here]

My name is Leviticus Markus Makpa, I am married to Benita Leviticus, we have 2 children, a boy, and a girl, we also have 8 foster children, 5 boys, and 3 girls.

I am a missionary working in Niger state, Nigeria among Kambari, Dukkawa, Fulani, and Hausa in the villages around Rijau and Kontagora Local Government Niger state Nigeria.

My wife and I are committed to reaching out to the unreached with the gospel of Christ through rural evangelism, discipleship, and establishing fellowship centers were necessary.

We work mostly with Children and teenagers in the remote areas of Niger State, Nigeria.
We have established free schooling to these villagers. 
My wife trains the ladies of the village in appropriate dressing. 
We also do vocational training for the youths. 
We drill boreholes for those who do not have access to good drinking water.

We are committed to:
Training this young one through discipleship.
Evangelizing discipleship and plant churches were necessary.
Serve as facilitators to existing denominations.
Reaching the unreached through outreaches
Help the unreached people in remote areas acquire vocations for livelihood through training in various skill

**Comment by sanmiayotunde** [comment]
Thanks @emmanlex

**Comment by sanmiayotunde** [comment]
@emmanlex  Let's open a new issue for his interview. I agree and I have the same idea. He is too busy for a written interview. An oral interview is better. We can send him voice notes on WhatsApp because he may be out of reach from the network.

When he gets network, he can reply with a series of voice notes.
