### ISSUE TITLE
Create Website Title for DaBible Foundation 

### ISSUE THREAD

**Issue by sanmiayotunde** [sanmiayotunde/DaBible-Foundation#7]
@emmanlex We need to change the title of dabible foundation website, just like the same way we changed the meta-description.

From your research, you discussed that the title can be around 55 words. Provide a research-based long tail keyword that we can use as the title for DaBible Foundation.

AS-IS

![image](https://user-images.githubusercontent.com/23180033/106709662-7f5c2600-65ba-11eb-8643-b1a150fc7b69.png)

**Comment by emmanlex** [comment]
In my research I took a look at other similar websites, and I found out some the current inadequacies of our site. Presently our   home webpage has a very low page authority and low domain authority. We have only 36 links going in and out. We need a keyword that puts us in our niche and is something people are searching for. The keyphrase would be one that we attach to all our other pages especially to our apps pages.

![Yoruba](https://user-images.githubusercontent.com/50557337/107071933-11c31c00-67ab-11eb-80ef-5b14145e0751.png)
![bible](https://user-images.githubusercontent.com/50557337/107071935-11c31c00-67ab-11eb-9eac-895f0a3beea6.png)
![audiobible](https://user-images.githubusercontent.com/50557337/107071936-11c31c00-67ab-11eb-8b1d-a4b0da1f3864.png)
![34](https://user-images.githubusercontent.com/50557337/107071938-11c31c00-67ab-11eb-9ed8-04f45970829f.png)




![Pidgin Link ](https://user-images.githubusercontent.com/50557337/107071927-1091ef00-67ab-11eb-8fbe-16d0c44562e7.png)
![Youversion PA](https://user-images.githubusercontent.com/50557337/107071929-112a8580-67ab-11eb-816e-21786bbc9ec1.png)
![PA](https://user-images.githubusercontent.com/50557337/107071931-112a8580-67ab-11eb-9f10-2007c36925a6.png)

**Comment by emmanlex** [comment]
@sanmiayotunde I would require access to the google analytics to further my keywords research.

**Comment by sanmiayotunde** [comment]
> @sanmiayotunde I would require access to the google analytics to further my keywords research.

open an issue for this request

**Comment by emmanlex** [comment]
This first MVP (minimum viable product).
**Title tag...**
Audio Bible in Yoruba & Pidgin... | DaBible Foundation

**Comment by emmanlex** [comment]
Second MVP (minimum viable product).
**Title tag**
Free Audio Bible in Yoruba & Pidgin | DaBible Foundation

**Comment by sanmiayotunde** [comment]
> Second MVP (minimum viable product).
> **Title tag**
> Free Audio Bible in Yoruba & Pidgin | DaBible Foundation

I think this one is perfect. Let's use it
